### ISSUE TITLE
Coap Pub Sampler - Unable to Edit payload

### ISSUE THREAD

**Issue by Tushar9029** [emqtt/coap-jmeter#1]
Hi Team,

I have created Jmeter Coap plugin using your code.
However ,after integrating with Jmeter,I am not able to edit payload .

I have to put specific string in payload body and I have selected String as payload type.

Please provide proper code to resolve the issue.

After saving Jmx script payload is getting default as String

**Comment by desireesantos** [comment]
Please take a look in this[ pull request ](https://github.com/xmeter-net/coap-jmeter/pull/2/commits/9ca63a5984ce58fc215fa7757c63d59a38fbc379).
You'll find the solution to fix this problem!

**Comment by desireesantos** [comment]
Hi @chongyuanyin,
This issue was fixed, what do you think to close this issue?

**Comment by Tushar9029** [comment]
Yes you can close the issue.Its working fine now
